Repository fga-eps-mds/2020.1-VC_Gestor-FrontEnd, pull requests merged in 2020-11, with the labels that each got.

#19 Issue 132 news management
  src/App.js
  src/components/components/CardBenefit.js
  src/components/components/EditNewsForm.js
  src/components/components/Sidebar.js
  src/components/components/editNewsForm.css
  src/components/pages/GerenciamentoNoticias.js
  src/components/pages/NewsEdit.js
  src/components/pages/Option2.js
  src/components/pages/gerenciamentoNoticias.css
  src/services/apiNoticias.js
Labels: Desenvolvimento, MDS, Sprint 9, User Story

#20 Issue 132 news creation
  package-lock.json
  package.json
  src/App.js
  src/assets/camera.png
  src/components/components/Forms.js
  src/components/components/NewsForm.js
  src/components/components/Sidebar.js
  src/components/pages/Beneficios.css
  src/components/pages/BeneficiosCriar.js
  src/components/pages/CreateNews.css
  src/components/pages/CreateNews.js
  src/services/apiNoticias.js
Labels: Desenvolvimento, MDS

#21 Issue 134 - troca de dados do usuário
  package-lock.json
  package.json
  public/css/sidebar.css
  src/App.js
  src/components/components/Sidebar.js
  src/components/perfil/perfil.css
  src/components/perfil/perfil.js
Labels: Desenvolvimento, MDS, Sprint 8
