Repository fga-eps-mds/2020.1-VC_Gestor-FrontEnd, pull requests merged in 2020-12, with the labels that each got.

#31 Issue 155 integration posts
  .nyc_output/b17894c2-adc9-45c8-9069-0688e9ec8e58.json
  .nyc_output/processinfo/b17894c2-adc9-45c8-9069-0688e9ec8e58.json
  .nyc_output/processinfo/index.json
  src/App.js
  src/components/components/estiloPostagem.css
  src/components/pages/Anuncio.js
  src/components/pages/RelatorioDeDados.js
  src/components/pages/RelatorioDeStatus.js
  src/components/pages/TabelaPosts.js
  src/services/apiPostagem.js
Labels: Desenvolvimento, MDS

#32 [WIP] Gerar .json com métricas pelo sonar
  .travis.yml
  deploy.sh
  docker_deploy.sh
Labels: enhancement

#33 Issue 160 Redirect page
  .nyc_output/aacbe1ec-87ec-44fa-b5ae-707fcdcd1a7c.json
  .nyc_output/processinfo/aacbe1ec-87ec-44fa-b5ae-707fcdcd1a7c.json
  .nyc_output/processinfo/index.json
  src/components/components/NewsForm.js
Labels: HotFix, MDS, Refatoração

#45 [HOTFIX 178] Redirecionamento, remoção e icone de exclusão
  src/components/components/EditBenefitForm.js
  src/components/pages/Anuncio.js
  src/components/pages/Beneficios.css
  src/components/pages/BeneficiosEditar.js
Labels: Desenvolvimento, HotFix

#54 Issue 186 fix colors
  public/css/sidebar.css
  src/App.js
  src/components/Home/home.css
  src/components/components/Sidebar.js
  src/components/components/cardBenefit.css
  src/components/components/estiloPostagem.css
  src/components/login/Login.css
  src/components/pages/Anuncio.css
  src/components/pages/Anuncio.js
  src/components/pages/Beneficios.css
  src/components/pages/BeneficiosGerenciar.js
  src/components/pages/CreateNews.css
  src/components/pages/GerenciamentoNoticias.js
  src/components/pages/RelatorioDeDados.css
  src/components/pages/RelatorioDeDados.js
  src/components/pages/RelatorioDeStatus.css
  src/components/pages/RelatorioDeStatus.js
  src/components/pages/gerenciamentoNoticias.css
  src/components/perfil/perfil.css
  src/fonts/UnB-Office_Bold.ttf
  src/fonts/UnB-Office_Italic.ttf
  src/fonts/UnB-Office_Regular.ttf
  src/fonts/UnBPro_Black.otf
  src/fonts/UnBPro_Bold.otf
  src/fonts/UnBPro_BoldItalic.otf
  src/fonts/UnBPro_Italic.otf
  src/fonts/UnBPro_Light.otf
  src/fonts/UnBPro_Regular.otf
  src/index.css
  src/index.js
  test/RelatorioDeStatus.test.js
Labels: HotFix, MDS
